name: Chore
description: For requesting chores, such as cleaning up code.
title: 'Chore: '
labels: [👀 needs triage]
body:
  - type: markdown
    attributes:
      value: '#### Thanks for taking the time to fill out this issue'
  - type: textarea
    id: description
    attributes:
      label: What work needs to be performed?
      description: Provide a clear and concise explanation of the work to be performed.
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this chore?
    validations:
      required: false
