name: 📝 Documentation
description: Request an update to invalid/outdated documentation
title: 'Docs: '
labels: [👀 needs triage, 📝 documentation]
body:
  - type: markdown
    attributes:
      value: '#### Thanks for taking the time to fill out this docs issue!'
  - type: textarea
    id: doc_error_description
    attributes:
      label: What is incorrect in the documentation?
      description: Please explain the information that is incorrect in the documentation, and why you think it needs to be updated.
    validations:
      required: true
  - type: textarea
    id: expected_information
    attributes:
      label: What should that text say?
      description: Provide the information that the documentation should actually contain instead of the incorrect content.
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this inaccuracy?
    validations:
      required: false
