name: Feature request
description: Suggest features, propose improvements, discuss new ideas for this project
title: '[FEAT] - '
labels: ['🚦 status: awaiting triage']
body:
  - type: markdown
    attributes:
      value: '# Feature request'
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
      description: Be as detailed as possible here. What would you like this application to do? How should you, as a user, interact with this feature? How can it benefit other users?
    validations:
      required: true
  - type: textarea
    id: possible_impl
    attributes:
      label: Possible implementation
      description: Not obligatory, but suggest an idea for implementing addition or change
    validations:
      required: false
  - type: textarea
    id: extra_info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this feature?
    validations:
      required: false
