name: Other
description: Use this for any other issues. PLEASE do not create blank issues
title: "[OTHER] - <other description>"
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issue_description
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
