
name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hi! Thank you for raising an issue.
            If this is a bug report, please include as much info as you can to help us debug the problem.
          pr-message: |
            Hi! Thank you very much for your contribution.
            
            If you are fixing a bug, please reference the issue number in the description.
            
            If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.
            The best way to do this is to raise an issue, if you have already done that, then thank you!
